# -*- coding: utf-8 -*-
"""MainExampleProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MiFipz6-PQHEVOGbdMadIBbaZlA2mAry
"""

import cv2
from google.colab.patches import cv2_imshow
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
filePath='/content/drive/MyDrive/Exmaple Example Project Test/ExampleTest1.jpeg'








img=cv2.imread(filePath)
black=np.array([0,0,0])
#print(img.shape)
for i in range(img[0]):
  for j in range(img[1]):
    if np.array_equal(img[i,j],black)==False:
      print(i,j,img[i,j])

##print(img[0,0])
##print(img.shape[0])
##cv2_imshow(img)

from google.colab import drive
drive.mount('/content/drive')